version: '3.4'

services:
  espadanegra:
    image: espadanegra
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file: 
      - .env
    restart: always
    ports: 
      - "${PORT}:${PORT}"
