version: '3.4'

services:
  server:
    build:
      context: .
      dockerfile: ./docker/server/Dockerfile
    env_file: 
      - .env
    restart: always
    ports: 
      - "${PORT_SERVER}:${PORT_SERVER}"
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    env_file: 
      - .env
    restart: always
    ports: 
      - "${PORT_WEB}:80"
